
_security_login:
    path:  /login
    defaults: { _controller: "ILCSecurityBundle:Security:login" }

_security_check:
    path:  /login_check
    methods: [POST]


_security_logout:
    path:  /logout
